import JSZip from "jszip";
import type { ComponentHierarchy, PipelineOutput } from "@/types/pipeline";

export async function downloadProjectZip(files: Record<string, string>, productName: string) {
  const zip = new JSZip();
  const folder = zip.folder("bridgeview-generated");

  folder?.file(
    "package.json",
    JSON.stringify(
      {
        name: "bridgeview-generated-ui",
        private: true,
        version: "1.0.0",
        scripts: { dev: "vite", build: "vite build" },
        dependencies: {
          react: "^19.0.0",
          "react-dom": "^19.0.0",
        },
        devDependencies: {
          typescript: "^5.8.2",
          vite: "^6.2.0",
          "@vitejs/plugin-react": "^4.3.4",
          tailwindcss: "^3.4.17",
        },
      },
      null,
      2,
    ),
  );

  for (const [filePath, content] of Object.entries(files)) {
    folder?.file(filePath, content);
  }

  folder?.file(
    "README.md",
    `# ${productName}\n\nGenerated by BridgeView AI — maritime UI from requirements.\n`,
  );

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${productName.replace(/\s+/g, "-").toLowerCase()}-bridgeview.zip`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function downloadJson(filename: string, data: unknown) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function downloadAllCode(files: Record<string, string>) {
  const combined = Object.entries(files)
    .map(([path, content]) => `// === ${path} ===\n${content}`)
    .join("\n\n");
  const blob = new Blob([combined], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "bridgeview-generated-code.txt";
  anchor.click();
  URL.revokeObjectURL(url);
}

export function buildExportPayload(result: PipelineOutput) {
  return {
    hierarchy: result.componentHierarchy,
    files: result.generatedFiles,
    analysis: result.productAnalysis,
  };
}
