import { z } from "zod";
import { grokStructuredOutput, isGrokEnabled } from "@/lib/grok";
import { toPascalCase } from "@/lib/utils";
import type { RequirementsAnalysis, WidgetNode } from "@/types/pipeline";

const ReactExportSchema = z.object({
  files: z.record(z.string()),
});

function componentTsx(name: string, node: WidgetNode): string {
  const borderAccent =
    node.type === "alert"
      ? "border-amber-500/50 bg-amber-950/30"
      : node.type === "metric"
        ? "border-cyan-500/50 bg-cyan-950/20"
        : "border-slate-700 bg-slate-900/60";

  return `import type { ReactNode } from "react";

export interface ${name}Props {
  children?: ReactNode;
}

export function ${name}({ children }: ${name}Props) {
  return (
    <section className="rounded-xl border p-4 shadow-sm ${borderAccent}">
      <h3 className="text-lg font-semibold text-white">${node.title}</h3>
      <p className="mt-2 text-sm text-slate-300">${node.description}</p>
      {children}
    </section>
  );
}
`;
}

export function exportReactFilesFallback(widgetTree: WidgetNode[]): Record<string, string> {
  const componentFiles: Record<string, string> = {};

  for (const [index, node] of widgetTree.entries()) {
    const name = toPascalCase(node.title, index);
    componentFiles[`components/${name}.tsx`] = componentTsx(name, node);
  }

  const imports = widgetTree
    .map((node, index) => {
      const name = toPascalCase(node.title, index);
      return `import { ${name} } from "./components/${name}";`;
    })
    .join("\n");

  const usage = widgetTree
    .map((node, index) => {
      const name = toPascalCase(node.title, index);
      return `      <${name} />`;
    })
    .join("\n");

  componentFiles["Dashboard.tsx"] = `${imports}

export default function Dashboard() {
  return (
    <div className="min-h-screen bg-slate-950 p-6">
      <header className="mb-6 border-b border-slate-700 pb-4">
        <h1 className="text-2xl font-bold text-white">Maritime Operations Dashboard</h1>
        <p className="text-sm text-slate-400">Generated by BridgeView AI</p>
      </header>
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
${usage}
      </div>
    </div>
  );
}
`;

  componentFiles["App.tsx"] = `import Dashboard from "./Dashboard";

export default function App() {
  return <Dashboard />;
}
`;

  return componentFiles;
}

function normalizeGrokFiles(files: Record<string, string>): Record<string, string> {
  const normalized: Record<string, string> = {};
  for (const [path, content] of Object.entries(files)) {
    const key = path.replace(/^\.\//, "");
    if (key.endsWith(".tsx") || key.endsWith(".jsx")) {
      normalized[key] = content;
    }
  }
  return normalized;
}

export async function exportReactFiles(
  widgetTree: WidgetNode[],
  productAnalysis?: RequirementsAnalysis,
): Promise<Record<string, string>> {
  if (!isGrokEnabled()) {
    return exportReactFilesFallback(widgetTree);
  }

  try {
    const result = await grokStructuredOutput(
      ReactExportSchema,
      `You are a senior React developer building a maritime dashboard.

Generate production-ready React 19 + TypeScript + Tailwind CSS files.

Product: ${productAnalysis?.product_name ?? "Maritime Operations Dashboard"}
Widget tree (JSON):
${JSON.stringify(widgetTree, null, 2)}

Requirements:
- Return a "files" map: keys are paths like "App.tsx", "Dashboard.tsx", "components/VoyageTrackingCard.tsx".
- Each component file: named export, Props interface, Tailwind className styling (dark slate maritime theme).
- Dashboard.tsx: imports all widgets, responsive grid layout, maritime header with product name.
- App.tsx: renders Dashboard as default export.
- Valid TSX only; no markdown fences.`,
    );

    const files = normalizeGrokFiles(result.files);
    if (!files["App.tsx"] || !files["Dashboard.tsx"]) {
      return exportReactFilesFallback(widgetTree);
    }
    return files;
  } catch {
    return exportReactFilesFallback(widgetTree);
  }
}
